### ISSUE TITLE
nRF52832 HID keyboardReport failed

### ISSUE THREAD

**Issue by shaoyuan1943** [hathach/mynewt-tinyusb-example#3]
Hi, hathach. I'm so sorry to bother you on github. I have a question I want to your help, please.

I want to use two nRF52832 boards to build bluetooth-keyboard.

One nRF52832 is central(right hand), one is peripheral(left hand), right hand connect left hand by UART and read left hand key matrix, at last, right hand send key matrix by bluetooth-hid to PC.

The problem is: when two nRF52832 board connected and right hand read key matrix succeed, but right hand HID send key matrix failed, I don't know why, I can't found any documents for that.

Following is my code:

1. right hand

void setup(){
  // to other things...
  Bluefruit.begin(1, 1);
  
  // to other things...
  hid.begin();
  
  // to other things...
}

void loop(){
  // the problem is hid.keyboardReport return false
  bool reported = hid.keyboardReport(mods, report);
}

2. left hand

void setup(){
  // to other things...
  Bluefruit.begin();
  
  // to other things...
  hid.begin();
  
  // to other things...
}

void loop(){
}

The complete code is here: https://gist.github.com/wez/b30683a4dfa329b86b9e0a2811a8c593

PS: If you don't like that, I will close this issue later.

Best regards.
lennon.c

**Comment by hathach** [comment]
Inappropriate repo

**Comment by shaoyuan1943** [comment]
Thank your reply :)
